// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// initFactories
void initFactories(std::string data_folder);
RcppExport SEXP _flowshopNehBasedHeuristicRecommendation_initFactories(SEXP data_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type data_folder(data_folderSEXP);
    initFactories(data_folder);
    return R_NilValue;
END_RCPP
}
// solveFSP
List solveFSP(std::string mh, Rcpp::CharacterVector rproblem, long seed, Rcpp::CharacterVector rparams, bool verbose);
RcppExport SEXP _flowshopNehBasedHeuristicRecommendation_solveFSP(SEXP mhSEXP, SEXP rproblemSEXP, SEXP seedSEXP, SEXP rparamsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type mh(mhSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type rproblem(rproblemSEXP);
    Rcpp::traits::input_parameter< long >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type rparams(rparamsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(solveFSP(mh, rproblem, seed, rparams, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sampleSolutionStatisticsFLA
List sampleSolutionStatisticsFLA(std::string dataFolder, Rcpp::CharacterVector rproblem, long noSamples, long seed);
RcppExport SEXP _flowshopNehBasedHeuristicRecommendation_sampleSolutionStatisticsFLA(SEXP dataFolderSEXP, SEXP rproblemSEXP, SEXP noSamplesSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dataFolder(dataFolderSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type rproblem(rproblemSEXP);
    Rcpp::traits::input_parameter< long >::type noSamples(noSamplesSEXP);
    Rcpp::traits::input_parameter< long >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleSolutionStatisticsFLA(dataFolder, rproblem, noSamples, seed));
    return rcpp_result_gen;
END_RCPP
}
// sampleRandomWalk
std::vector<double> sampleRandomWalk(std::string dataFolder, Rcpp::CharacterVector rproblem, int noSamples, std::string samplingStrat, long seed);
RcppExport SEXP _flowshopNehBasedHeuristicRecommendation_sampleRandomWalk(SEXP dataFolderSEXP, SEXP rproblemSEXP, SEXP noSamplesSEXP, SEXP samplingStratSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dataFolder(dataFolderSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type rproblem(rproblemSEXP);
    Rcpp::traits::input_parameter< int >::type noSamples(noSamplesSEXP);
    Rcpp::traits::input_parameter< std::string >::type samplingStrat(samplingStratSEXP);
    Rcpp::traits::input_parameter< long >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleRandomWalk(dataFolder, rproblem, noSamples, samplingStrat, seed));
    return rcpp_result_gen;
END_RCPP
}
// enumerateAllFitness
std::vector<double> enumerateAllFitness(Rcpp::CharacterVector rproblem);
RcppExport SEXP _flowshopNehBasedHeuristicRecommendation_enumerateAllFitness(SEXP rproblemSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type rproblem(rproblemSEXP);
    rcpp_result_gen = Rcpp::wrap(enumerateAllFitness(rproblem));
    return rcpp_result_gen;
END_RCPP
}
// enumerateSolutions
List enumerateSolutions(Rcpp::List fspInstance, Rcpp::CharacterVector fspProblem);
RcppExport SEXP _flowshopNehBasedHeuristicRecommendation_enumerateSolutions(SEXP fspInstanceSEXP, SEXP fspProblemSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fspInstance(fspInstanceSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type fspProblem(fspProblemSEXP);
    rcpp_result_gen = Rcpp::wrap(enumerateSolutions(fspInstance, fspProblem));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flowshopNehBasedHeuristicRecommendation_initFactories", (DL_FUNC) &_flowshopNehBasedHeuristicRecommendation_initFactories, 1},
    {"_flowshopNehBasedHeuristicRecommendation_solveFSP", (DL_FUNC) &_flowshopNehBasedHeuristicRecommendation_solveFSP, 5},
    {"_flowshopNehBasedHeuristicRecommendation_sampleSolutionStatisticsFLA", (DL_FUNC) &_flowshopNehBasedHeuristicRecommendation_sampleSolutionStatisticsFLA, 4},
    {"_flowshopNehBasedHeuristicRecommendation_sampleRandomWalk", (DL_FUNC) &_flowshopNehBasedHeuristicRecommendation_sampleRandomWalk, 5},
    {"_flowshopNehBasedHeuristicRecommendation_enumerateAllFitness", (DL_FUNC) &_flowshopNehBasedHeuristicRecommendation_enumerateAllFitness, 1},
    {"_flowshopNehBasedHeuristicRecommendation_enumerateSolutions", (DL_FUNC) &_flowshopNehBasedHeuristicRecommendation_enumerateSolutions, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_flowshopNehBasedHeuristicRecommendation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
