# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initFactories <- function(data_folder) {
    invisible(.Call(`_flowshopNehBasedHeuristicRecommendation_initFactories`, data_folder))
}

solveFSP <- function(mh, rproblem, seed, rparams, verbose = FALSE) {
    .Call(`_flowshopNehBasedHeuristicRecommendation_solveFSP`, mh, rproblem, seed, rparams, verbose)
}

sampleSolutionStatisticsFLA <- function(dataFolder, rproblem, noSamples, seed) {
    .Call(`_flowshopNehBasedHeuristicRecommendation_sampleSolutionStatisticsFLA`, dataFolder, rproblem, noSamples, seed)
}

sampleRandomWalk <- function(dataFolder, rproblem, noSamples, samplingStrat, seed) {
    .Call(`_flowshopNehBasedHeuristicRecommendation_sampleRandomWalk`, dataFolder, rproblem, noSamples, samplingStrat, seed)
}

enumerateAllFitness <- function(rproblem) {
    .Call(`_flowshopNehBasedHeuristicRecommendation_enumerateAllFitness`, rproblem)
}

enumerateSolutions <- function(fspInstance, fspProblem) {
    .Call(`_flowshopNehBasedHeuristicRecommendation_enumerateSolutions`, fspInstance, fspProblem)
}

